// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalPortfolioWebSite.Data.Concrete.EntityFramework.Context;

#nullable disable

namespace PersonalPortfolioWebSite.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220811115336_three")]
    partial class three
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PersonalPortfolioWebSite.Entities.Concrete.Models.About", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CvEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CvTurk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("About");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CvEnglish = "Hello, my name is Ömer Faruk Benli, I was born on 26.01.1993 in Istanbul. My university education, Sakarya  An average of 3.52 processes was completed in the Department of University-Labor Economy and Industry. I started my master's degree again at Sakarya University and completed my master's thesis. I am not completing and graduating in 2023. For 3.5 years post-university I worked as private security, management evaluations. software in 2021 No preparation has been made for filing. Elevator com, backend and I develop and publish the front parts. C# as software language, C# as Framework I am focused on Asp.Net and Angular",
                            CvTurk = "Merhabalar, kendimi kısaca tanıtmam gerekirse adım ve soyadım Ömer Faruk Benli, 26.0.1993 tarihinde, İstanbul'da doğdum. Üniversite eğitimimi, Sakarya Üniversitesi-Çalışma Ekonomisi ve Endüstri İlişkileri Bölümünde 3.52 not ortalaması ile tamamladım. Yüksek Lisansıma yine Sakarya Üniversitesinde başlamış olup, yüksek lisans tezini 2023 yılında tamamlamayıp mezun olmayı planlamaktayım. Üniversite sonrası 3.5 yıl boyunca özel sektörde, gayrimenkul değerleme uzmanı olarak görev yaptım. 2021 yılında yazılım alanında kariyer yapmak adına yazılım eğitimi almaya başladım. Asansor com adlı siteyi, backend ve frontend kısımlarını geliştirip yayınladım. Yazılım dili olarak C#, Framework olarak Asp.Net ve Angular'a yoğunlaşmış bulunmaktayım.  "
                        });
                });

            modelBuilder.Entity("PersonalPortfolioWebSite.Entities.Concrete.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contact");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "İstanbul/Ümraniye",
                            FullName = "Ömer Faruk Benli",
                            Phone = "0(544) 205 98 45"
                        });
                });

            modelBuilder.Entity("PersonalPortfolioWebSite.Entities.Concrete.Models.Home", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TitleOne")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleTwo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Home");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TitleOne = "Merhaba, kişisel websiteme hoş geldiniz. Hakkımda sekmesinden benim ile ilgili daha fazla bilgi edinebilir, İletişim sekmesinden,iletişim bilgieri ve sosyal ağ adreslerime ulaşabilirsiniz. iletişim bilgieri ve sosyal ağ adreslerime ulaşabilirsiniz. repolara göz gezdirebilirsiniz  ",
                            TitleTwo = "Hello, welcome to my personal website. More about me on the About me tab You can get more information, from the Contact tab, You can reach my contact information and social network addresses. From the My Repos tab, you can browse through the repos that I have published on the github network"
                        });
                });

            modelBuilder.Entity("PersonalPortfolioWebSite.Entities.Concrete.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Link");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Odaklandığım yazılım dili, frameworkler ve veri tabanları"
                        },
                        new
                        {
                            Id = 2,
                            Name = "My focus is on Software Languages, Frameworks and Databases"
                        });
                });

            modelBuilder.Entity("PersonalPortfolioWebSite.Entities.Concrete.Models.Repo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ContentSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Repo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContentSummary = "Çoka çok ilişki kurularak, çoklu crud işlemleri yapıldı",
                            Title = "Crud-Many-to-Many",
                            Url = "https://github.com/omerfarukbenli/Crud-Many-to-Many"
                        },
                        new
                        {
                            Id = 2,
                            ContentSummary = "Asp.Net'te Authentication ve Authorization işlemleri yapıldı",
                            Title = "Asp.Net-6-Auth",
                            Url = "https://github.com/omerfarukbenli/Asp.Net-6-Auth"
                        },
                        new
                        {
                            Id = 3,
                            ContentSummary = "Asp.Net'te Crud operasyonları yapılarak öğrenci kayıt işlemleri yapıldı",
                            Title = "Asp.Net-6-Öğrenci-Kayıt-Sistemi",
                            Url = "https://github.com/omerfarukbenli/Asp.Net-6-OgrenciKayitSistemi-Backend-Frontend"
                        },
                        new
                        {
                            Id = 4,
                            ContentSummary = "Angular 14 frameworkü kullanılarak temel düzeyde crud işlemleri yapıldı",
                            Title = "Angular Crud",
                            Url = "https://github.com/omerfarukbenli/Angular-Crud-islemleri"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
